export interface VendorDef {
  id: string;
  name: string;
  booth: string;
  type: "auction" | "vendor";
  category?: "vintage" | "modern" | "japanese" | "goldstar" | "slab";
  x: number;
  y: number;
  w: number;
  h: number;
  shape: "mega-island" | "arched" | "chamfered" | "compact" | "diamond" | "tower" | "wide-pavilion";
  color: string;
  rating: string;
  activeListings: string;
  completedTrans: string;
  specialties: string[];
  discountScore: number;
}

export const VENDORS: VendorDef[] = [
  {
    id: "auction",
    name: "MAIN STAGE & AUCTION ARENA",
    booth: "Zone 1",
    type: "auction",
    x: 40, y: 45, w: 160, h: 280,
    shape: "mega-island",
    color: "#ef4444",
    rating: "5.0 / 5",
    activeListings: "125 Grails Live",
    completedTrans: "50,000+",
    specialties: ["Live Auctions", "Celebrity Signings", "Trophy Card Reveals"],
    discountScore: 95,
  },
  {
    id: "vintagevault",
    name: "VINTAGEVAULT TCG",
    booth: "5B",
    type: "vendor",
    category: "vintage",
    x: 215, y: 42, w: 92, h: 86,
    shape: "arched",
    color: "#2dd4bf",
    rating: "4.8 / 5",
    activeListings: "3,450+ Items",
    completedTrans: "12,800+",
    specialties: ["WOTC Japanese (Kanji)", "e-Series (JPN)", "Neo Destiny"],
    discountScore: 75,
  },
  {
    id: "modernalt",
    name: "MODERN ALT ART VAULT",
    booth: "16",
    type: "vendor",
    category: "modern",
    x: 320, y: 44, w: 78, h: 90,
    shape: "chamfered",
    color: "#38bdf8",
    rating: "4.9 / 5",
    activeListings: "2,400+ Singles",
    completedTrans: "11,500+",
    specialties: ["Giratina V Alt", "Moonbreon", "Rayquaza VMAX Alt"],
    discountScore: 82,
  },
  {
    id: "japanese",
    name: "JAPANESE HIGH CLASS HUB",
    booth: "46",
    type: "vendor",
    category: "japanese",
    x: 412, y: 38, w: 106, h: 94,
    shape: "mega-island",
    color: "#38bdf8",
    rating: "4.8 / 5",
    activeListings: "3,800+ Items",
    completedTrans: "18,400+",
    specialties: ["Shiny Treasure EX", "VSTAR Universe", "Terastal Festival EX"],
    discountScore: 78,
  },
  {
    id: "brodes",
    name: "BRODES TCG SYNDICATE",
    booth: "15",
    type: "vendor",
    category: "modern",
    x: 530, y: 48, w: 74, h: 76,
    shape: "compact",
    color: "#38bdf8",
    rating: "4.8 / 5",
    activeListings: "1,900+ Items",
    completedTrans: "9,300+",
    specialties: ["Japanese S&V Master Sets", "Promo Cards", "High Grade Slabs"],
    discountScore: 76,
  },
  {
    id: "goldstar",
    name: "GOLD STAR COLLECTORS",
    booth: "6B",
    type: "vendor",
    category: "goldstar",
    x: 210, y: 142, w: 94, h: 84,
    shape: "diamond",
    color: "#f472b6",
    rating: "4.8 / 5",
    activeListings: "1,120+ Items",
    completedTrans: "6,900+",
    specialties: ["Gold Star Espeon", "Shining Charizard", "Crystal Lugia"],
    discountScore: 76,
  },
  {
    id: "uds",
    name: "UDS COLLECTIBLES & SLABS",
    booth: "8B",
    type: "vendor",
    category: "modern",
    x: 320, y: 140, w: 78, h: 92,
    shape: "tower",
    color: "#38bdf8",
    rating: "4.8 / 5",
    activeListings: "2,100+ Slabs",
    completedTrans: "11,800+",
    specialties: ["PSA 10 Modern Grails", "Sun & Moon Alt Arts", "Tag Team Promos"],
    discountScore: 74,
  },
  {
    id: "wikrats",
    name: "WIKRATS POKÉMON EMPORIUM",
    booth: "8A",
    type: "vendor",
    category: "modern",
    x: 412, y: 148, w: 90, h: 76,
    shape: "wide-pavilion",
    color: "#38bdf8",
    rating: "4.7 / 5",
    activeListings: "1,350+ Items",
    completedTrans: "6,400+",
    specialties: ["Modern Alt Arts", "S&V ex Singles", "Promo Cards"],
    discountScore: 68,
  },
  {
    id: "trainertower",
    name: "TRAINER TOWER JAPAN",
    booth: "5D",
    type: "vendor",
    category: "japanese",
    x: 516, y: 138, w: 90, h: 92,
    shape: "mega-island",
    color: "#38bdf8",
    rating: "4.8 / 5",
    activeListings: "2,100+ Items",
    completedTrans: "9,800+",
    specialties: ["Japanese SARs", "Pokemon Center Exclusives", "Terastal Festival"],
    discountScore: 74,
  },
  {
    id: "neodestiny",
    name: "NEO DESTINY SPECIALIST",
    booth: "8D",
    type: "vendor",
    category: "japanese",
    x: 215, y: 242, w: 82, h: 88,
    shape: "arched",
    color: "#38bdf8",
    rating: "4.9 / 5",
    activeListings: "1,420+ Items",
    completedTrans: "8,400+",
    specialties: ["Neo Destiny Shinings", "Neo Revelation Holos", "1st Edition Neo Classics"],
    discountScore: 82,
  },
  {
    id: "specs",
    name: "SPECS GRADED GRAILS",
    booth: "8C",
    type: "vendor",
    category: "modern",
    x: 308, y: 246, w: 96, h: 78,
    shape: "wide-pavilion",
    color: "#38bdf8",
    rating: "4.9 / 5",
    activeListings: "3,100+ Items",
    completedTrans: "16,200+",
    specialties: ["PSA 10 Modern", "BGS 9.5+", "CGC Pristine"],
    discountScore: 82,
  },
  {
    id: "aqua",
    name: "AQUA TCG BOOTH",
    booth: "9A",
    type: "vendor",
    category: "modern",
    x: 418, y: 246, w: 80, h: 84,
    shape: "chamfered",
    color: "#2dd4bf",
    rating: "4.7 / 5",
    activeListings: "1,800+ Items",
    completedTrans: "7,200+",
    specialties: ["Water-type Collection", "Theme Deck Singles", "Budget Playsets"],
    discountScore: 65,
  },
  {
    id: "battlebond",
    name: "BATTLE BOND COLLECTIBLES",
    booth: "9B",
    type: "vendor",
    category: "modern",
    x: 512, y: 245, w: 90, h: 82,
    shape: "compact",
    color: "#38bdf8",
    rating: "4.8 / 5",
    activeListings: "2,300+ Items",
    completedTrans: "10,100+",
    specialties: ["Trainer Gallery", "Radiant Cards", "VSTAR/VMAX Singles"],
    discountScore: 72,
  },
  {
    id: "mysticgrails",
    name: "MYSTIC GRAILS JAPAN",
    booth: "7C",
    type: "vendor",
    category: "japanese",
    x: 210, y: 338, w: 94, h: 88,
    shape: "diamond",
    color: "#c084fc",
    rating: "4.9 / 5",
    activeListings: "2,600+ Items",
    completedTrans: "14,500+",
    specialties: ["Japanese AR/SAR Hits", "Pokemon Center Stamp", "Vending Series"],
    discountScore: 80,
  },
  {
    id: "carbanda",
    name: "CARBANDA TCG",
    booth: "7B",
    type: "vendor",
    category: "modern",
    x: 318, y: 344, w: 80, h: 82,
    shape: "compact",
    color: "#f472b6",
    rating: "4.9 / 5",
    activeListings: "2,200+ Cards",
    completedTrans: "12,100+",
    specialties: ["Modern ex Singles", "Art Rares", "Reverse Holo Playsets"],
    discountScore: 84,
  },
  {
    id: "pokecenter",
    name: "POKEMON CENTER OSAKA",
    booth: "10A",
    type: "vendor",
    category: "japanese",
    x: 410, y: 336, w: 104, h: 92,
    shape: "mega-island",
    color: "#f472b6",
    rating: "4.8 / 5",
    activeListings: "3,000+ Items",
    completedTrans: "20,100+",
    specialties: ["PC Stamp Promos", "Japanese ETB Singles", "431 Stamp Cards"],
    discountScore: 86,
  },
  {
    id: "alphagrails",
    name: "ALPHA GRAILS TCG",
    booth: "5A",
    type: "vendor",
    category: "modern",
    x: 526, y: 342, w: 80, h: 84,
    shape: "chamfered",
    color: "#38bdf8",
    rating: "4.9 / 5",
    activeListings: "3,200+ Items",
    completedTrans: "19,500+",
    specialties: ["Modern Secret Rares", "Gold Cards", "Hyper Rares"],
    discountScore: 82,
  },
];
